[package]
name = "cmudict"
version = "0.1.0"
authors = ["Paul Woolcock <paul@woolcock.us>"]

[dependencies]
cmudict_core = { path = "../cmudict_core" }
indexed-line-reader = "0.2.0"
error-chain = "0.11.0"
reqwest = "0.8.2"
tempdir = "0.3.5"
